### ISSUE TITLE
Baidu Map in language files

### ISSUE THREAD

**Issue by codersclub** [kindsoft/kindeditor#168]
I see all the language files have Baidu Map inside:

KindEditor.each(KindEditor.options.items, function(i, name) {
	if (name == 'baidumap') {
		KindEditor.options.items[i] = 'map';
	}
});

Only zh-CN.js language does not have that code inside.

Why not move that code block into the main editor file?
Because of that code is not a language at all...

**Comment by luolonghao** [comment]
because english users don't need baidumap, if you don't like it, can remove the code, and replace baidumap to map in the KindEditor.options.items.
