### ISSUE TITLE
V4.1.10 编辑html代码时img元素的src问题

### ISSUE THREAD

**Issue by Baozi2** [kindsoft/kindeditor#194]
使用编辑html代码功能时，如果代码是 
```<img src="https:////img.alicdn.com/bao/uploaded/TB1kM8EIFXXXXbMXpXXSutbFXXX.jpg" data-cke-saved-src="/images/201510/body/201510131110363_6370.jpg" >```
这个样子的，最终会被转换为
```<img data-ke-src="/images/201510/body/201510131110363_6370.jpg" data-cke-saved-src="/images/201510/body/201510131110363_6370.jpg" src="/images/201510/body/201510131110363_6370.jpg">```
可以看到是以img元素中，属性中最后一个以src结尾的属性的值作为src属性的值，此时出现img元素src不正确的问题

**Comment by luolonghao** [comment]
确实有这个问题，感谢反馈。

**Comment by cng1985** [comment]
我也遇到这样的问题
