### ISSUE TITLE
IE9和IE10下使用纯文本粘贴报错：对象不支持“moveToElementText”

### ISSUE THREAD

**Issue by ChengYiFan** [kindsoft/kindeditor#222]
如图所示：

![e78d00997f503eb72caebda0a8d2f601](https://cloud.githubusercontent.com/assets/14120250/17324354/b8009f98-58d8-11e6-909e-0b796eed5e52.jpg)

**Comment by ChengYiFan** [comment]
已经排查到原因，在IE9和IE10浏览器中，不能正确获取到TextRange对象。原因是_IERANGE的判断方式错误。修正后即可。

**Comment by tofdragon** [comment]
@ChengYiFan  您好  IE11 下面依据你github修改的代码会报错 粘贴的时候会存在问题
