### ISSUE TITLE
批量图片上传失效  - 添加图片按钮无法显示

### ISSUE THREAD

**Issue by fufuok** [kindsoft/kindeditor#324]
![image](https://user-images.githubusercontent.com/4979407/104829829-a4f6e900-58b2-11eb-9e5b-71221fb6de47.png)

![image](https://user-images.githubusercontent.com/4979407/104830316-ac20f580-58b8-11eb-8b7f-7c5f80f4b73f.png)

![image](https://user-images.githubusercontent.com/4979407/104830324-c22eb600-58b8-11eb-9a1a-5b6e1bce3b11.png)

如题, 希望能修复~~

编辑器用在了很多网站中, 挺喜欢这简约, 精致的风格, 功能也全.

**Comment by fufuok** [comment]
KindEditor 4.1.11, KindEditor 4.1.12

**Comment by lukelhi** [comment]
我上周还好好的，这周就挂了，不能批量上传了。换了旧版支持flash的火狐浏览器还能用

**Comment by hulang** [comment]
@fufuok @lukelhi @zhangbianyu 我自己整合的。。。[https://gitee.com/hulangfy/kindeditor](https://gitee.com/hulangfy/kindeditor)
