### ISSUE TITLE
mac下面，qq拼音输入法，稍微快速的连续输入，会把英文字母也加到编辑器里面

### ISSUE THREAD

**Issue by luolonghao** [kindsoft/kindeditor#39]
http://code.google.com/p/kindeditor/issues/detail?id=274

**Comment by Scorpio-ljc** [comment]
你是如何解决这个问题的，我现在遇到一个问题是第一次页面加载编辑器输入内容会出现光标直接跳到最前面，而且会将中文转换为拼音
